version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pipenv install

      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile" }}